### ISSUE TITLE
Python Generator Not Generating Arrays of Correct Size

### ISSUE THREAD

**Issue by DJSteins** [oxfordcontrol/osqp#55] opened 2018-03-27 20:42 UTC
So I've been trying to use the Python script below to generate the OSQP code for my embedded system, but I've found that it has not been generating arrays of the correct size. More specifically, when I go into the generated `workspace.h` file, instead of having a P matrix of size 16 (4x4), it is only size 10. I am worried that these incorrect array sizes are being carried through the rest of `workspace.h` and possibly other parts of the generated code and are causing the solver to fail as a result of that.

```Python
# get an OSQP object
m = osqp.OSQP()

# linear cost term
q = np.zeros((1, 4))[0] + 1
# lower wheel acceleration constraint
l = np.zeros((1, 4))[0] + 1
# upper wheel acceleration constraint
u = np.zeros((1, 4))[0] + 1
# quadratic term
P = sparse.csc_matrix(np.zeros((4, 4)) + 1)
# A matrix for l <= Ax <= u
A = sparse.csc_matrix(np.zeros((4, 4)) + 1)

# setup the solver
m.setup(P=P, A=A, q=q, l=l, u=u)
# generate the C code in the folder that this file is run from.
m.codegen(os.getcwd(), parameters="matrices")
```

**Comment by goulart-paul** [comment] 2018-03-27 20:49
I suspect that this is because the solver assumes that P is symmetric and only requires the lower triangular part.   Is that the issue?   If so it is the expected behaviour.

**Comment by DJSteins** [comment] 2018-03-27 20:57
Oh that might be it. P is not supposed to be symmetric though in our case, so how would we change it to generate a full 16 size array?

**Comment by bstellato** [comment] 2018-03-27 21:02
Yes, this is the expected behavior. OSQP extracts the *upper triangular* part of P during the setup phase. I will add a couple of lines to the docs to make it clear.

Note that convex quadratic programs require P to be symmetric positive semidefinite. See the problem description on the [documentation website](osqp.readthedocs.io) and Section 4.4 of "[Convex Optimization](http://stanford.edu/~boyd/cvxbook/bv_cvxbook.pdf)," Boyd, Vandenberghe.

Are you sure P is non symmetric? In that case you might have a nonconvex problem.

**Comment by goulart-paul** [comment] 2018-03-27 21:13
Since P only ever appears in a quadratic form, it is always possible to symmetrize P to (P +P’)/2.   It never makes sense to use an asymmetric P.

In other words, just use the fact that 

x^T*P*x  = x^T*(P + P^T)*x / 2;

**Comment by DJSteins** [comment] 2018-03-28 00:15
I've followed your guys' advice, but it seems that I can only get the optimizer to work when P is the upper triangular of an identity matrix. Any reason that this might be happening?

**Comment by bstellato** [comment] 2018-03-28 00:18
Could you please provide a minimal working example where it does not work? Or the problem data `P`, `q`, `A`, `l`, `u` that cause the issue?

**Comment by DJSteins** [comment] 2018-03-28 00:22
P
[[2.000000, 1.206290, 0.029641, 0.563355]
 [1.206290, 2.000000, 1.036295, 0.029641]
 [0.029641, 1.036295, 2.000000, 1.206290]
 [0.563355, 0.029641, 1.206290, 2.000000]]

q
[[-2.046713, 0.228033, 3.834692, 2.356885]]

l
-3.000000 -3.000000 -3.000000 -3.000000 

u
3.000000 3.000000 3.000000 3.000000 

and A is just a 4x4 matrix of 1.0 in every entry

**Comment by DJSteins** [comment] 2018-03-28 00:40
When the C code is generated are there arrays that are generated based on the values in P, A, l, u, and q? Because I just put arbitrary values into P when I generated the code since when I run my software I update P on each tick of my main program loop.

**Comment by bstellato** [comment] 2018-03-28 03:25
This code works in my case. It compares the desktop solution with the one from the embedded code generator.

Note that the code generation folder cannot be the current directory since it gets deleted when you generate code. Hence you need to change the command `os.getcwd()` (see below).

```python
import osqp
import numpy as np
import scipy.sparse as sparse

# get an OSQP object
m = osqp.OSQP()

# linear cost term
q = np.array([-2.046713, 0.228033, 3.834692, 2.356885])
# lower wheel acceleration constraint
l = -3 * np.ones(len(q))
# upper wheel acceleration constraint
u = 3 * np.ones(len(q))
# quadratic term
P = sparse.csc_matrix([[2.000000, 1.206290, 0.029641, 0.563355],
                       [1.206290, 2.000000, 1.036295, 0.029641],
                       [0.029641, 1.036295, 2.000000, 1.206290],
                       [0.563355, 0.029641, 1.206290, 2.000000]])
# A matrix for l <= Ax <= u
A = sparse.csc_matrix(np.zeros((4, 4)) + 1)

# setup the solver
m.setup(P=P, A=A, q=q, l=l, u=u, verbose=False)
# generate the C code in the folder that this file is run from.
m.codegen('code', parameters="matrices")

# solve with osqp desktop
results_desktop = m.solve()

# Import embedded module and solve
import emosqp
[x, y, status_val, niter, time] = emosqp.solve()

# Compare results
print("Norm of optimal primal solution difference difference between desktop and embedded version = %.2e"
      % np.linalg.norm(results_desktop.x - x))
print("Norm of optimal dual solution difference difference between desktop and embedded version = %.2e"
      % np.linalg.norm(results_desktop.y - y))
```

**Comment by DJSteins** [comment] 2018-03-28 03:32
I don't know if it makes a difference, but we are actually intending to use the generated C code, not the emosqp file

**Comment by bstellato** [comment] 2018-03-28 03:43
It does not make a difference. The embedded code works anyway. In that example is in the `code` folder. After you run that python script, you can try the embedded code with:

```bash
➜  cd code/build
➜  cmake ..
-- We are on a Darwin system
-- Embedded is 2
-- Passing EMBEDDED flag to compiler
-- Disabling printing for embedded
-- Printing is OFF
-- Disabling profiling for embedded
-- Profiling is OFF
-- Floats are OFF
-- Long integers (64bit) are ON
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/user/Desktop/test_issue_github/code/build
➜  make
[  8%] Building C object CMakeFiles/emosqpstatic.dir/src/osqp/auxil.c.o
[ 16%] Building C object CMakeFiles/emosqpstatic.dir/src/osqp/lin_alg.c.o
[ 25%] Building C object CMakeFiles/emosqpstatic.dir/src/osqp/osqp.c.o
[ 33%] Building C object CMakeFiles/emosqpstatic.dir/src/osqp/proj.c.o
[ 41%] Building C object CMakeFiles/emosqpstatic.dir/src/osqp/scaling.c.o
[ 50%] Building C object CMakeFiles/emosqpstatic.dir/src/osqp/util.c.o
[ 58%] Building C object CMakeFiles/emosqpstatic.dir/src/osqp/suitesparse_ldl.c.o
[ 66%] Building C object CMakeFiles/emosqpstatic.dir/src/osqp/ldl.c.o
[ 75%] Building C object CMakeFiles/emosqpstatic.dir/src/osqp/kkt.c.o
[ 83%] Linking C static library out/libemosqpstatic.a
[ 83%] Built target emosqpstatic
[ 91%] Building C object CMakeFiles/example.dir/src/example.c.o
[100%] Linking C executable out/example
[100%] Built target example
➜  out/example
Status:                solved
Number of iterations:  25
Objective value:       -4.9527e+00
Primal residual:       1.8672e-15
Dual residual:         1.2340e-05
```

**Comment by DJSteins** [comment] 2018-03-28 03:50
Then I need to be able to link against this in my own CMake project and update the P, q, l, and u matrices on each tick of my main program loop. Should I link against libemosqpstatic.a?

**Comment by DJSteins** [comment] 2018-03-28 03:54
It's also worth mentioning we are using the `arm-none-eabi-gcc` compiler

**Comment by bstellato** [comment] 2018-03-28 14:08
You can either include the generated project as a submodule of your CMake configuration, or link against the library `libemosqpstatic.a`. The  compiler should not make a difference. It should be specified in your upper level CMakeLists.txt file. 

It seems the discussion is going off topic and it is no longer related to a bug. I suggest you to write a post on the [OSQP forum](https://groups.google.com/forum/#!forum/osqp) for general help. I am closing this issue for now.

**Closed** 2018-03-28 14:09 UTC
