### ISSUE TITLE
Should we expect OSQP_NON_CVX on all non-convex problems?

### ISSUE THREAD

**Issue by mlubin** [oxfordcontrol/osqp#86] opened 2018-08-26 15:51 UTC
OSQP is happy to minimize -x^2 and return 0 as the optimal solution. Is this expected or should it detect non-convexity?
```julia
using OSQP
m = OSQP.Model()
OSQP.setup!(m, P=spdiagm([-1.0]))
OSQP.warm_start_x!(m, [2.0])
results = OSQP.solve!(m)
@show results.info.status
```

**Comment by bstellato** [comment] 2018-08-26 16:31
The check on the current branch works when the residuals diverge. It is a bit naive.
@gbanjac added a proper check in branch `0.4.1`. It works when the factorization is performed.

Would you be able to try it? I believe it should detect the nonconvexity.

**Comment by gbanjac** [comment] 2018-08-26 20:54
The new check that @bstellato mentioned is done during the setup phase. The LDL factorization of the matrix (see [here](http://osqp.org/docs/solver/index.html#linear-system-solution)) should produce a diagonal matrix `D` with `n` positive and `m` negative diagonal entries given that `P+sigma*I` is positive definite. The check is based on counting the positive entries in `D`.

Note that this check will not work when `P` is not PSD and `P+sigma*I` is PD. However, the default value of `sigma` is `1e-6` and this should happen only when the distance between `P` and the PSD cone is very small.

I guess the only reliable way to detect non-convexity would be to compute the eigenvalue decomposition of `P`, but this is not what we want to do within OSQP.

**Comment by mlubin** [comment] 2018-09-05 16:37
> Would you be able to try it? 

Sorry, I haven't gotten to trying it yet because there are few manual steps to getting the Julia wrapper building an upstream branch instead of a release.

**Comment by mlubin** [comment] 2018-09-05 16:45
> Note that this check will not work when P is not PSD and P+sigma*I is PD. However, the default value of sigma is 1e-6 and this should happen only when the distance between P and the PSD cone is very small.

That's a reasonable check. What are the possible statuses reported when P is not PSD but P+sigma*I is PD? Could OSQP still return a solution that it reports is optimal but is not?

**Comment by bstellato** [comment] 2018-09-05 21:11
There might be cases where this test does not detect a matrix with a slightly negative eigenvalue. As @gbanjac mentioned, this happens when that eigenvalue is in absolute value less than `1e-06`. I think the only way to detect a non PSD matrix in 100% of the cases would be to perform an eigenvalue decomposition inside OSQP. However, we do not want to do that because it can be very slow.

Do you have QPs with these characteristics? Would it be possible for you to check if the problem is convex when you are building it? From which language are you calling OSQP?

**Comment by mlubin** [comment] 2018-09-05 21:47
> Do you have QPs with these characteristics? Would it be possible for you to check if the problem is convex when you are building it? From which language are you calling OSQP?

The issue is more about documentation than a specific instance/language interface. The discussion of [solver statuses](https://osqp.org/docs/interfaces/status_values.html) is confusing on a few points:

1. (Obvious) It's missing `OSQP_NON_CVX`. But anyway for the points below let's take the documentation from the source code as "problem non convex".
2. Does providing a non-convex problem to OSQP imply that `OSQP_NON_CVX` will be returned? Given the discussion above, the answer is "No, but it will be detected unless the smallest negative eigenvalue is greater than X." This should be documented somewhere.
3. What happens in the edge case that's not detected? From the discussion above it sounds like OSQP could report `OSQP_SOLVED` and return a solution that's not globally optimal. This should be documented somewhere.

This is meant only as constructive feedback about API issues that I expect other users will run into. Thanks for the responses so far :)

**Comment by goulart-paul** [comment] 2018-09-06 06:59
I do not think that is necessary to compute the full eigenvalue decomposition since we only want to know the most negative eigenvalue.

I think one could proceed as follows:

1) Compute the LDL decomposition of the KKT matrix and check the matrix inertia.   If it is as expected, then the smallest eigenvalue of P is not lower than $-\sigma$ (i.e. it is a certificate that P + \sigma I \succ 0).   If it is not, then fail with an error (this is what we do now).

2) Otherwise, set $H = - (P+\sigma I) + (trace(P) + n\sigma)*I$.   This should be positive semidefinite since (P+\sigma I) has all positive eigenvalues and $(\trace P + n\sigma)$ is their sum.   The eigenvector associated with the largest eigenvalue of $H$ is also the eigenvector associated with the smallest (i.e. most negative) eigenvalue of $P$.

3) Compute the dominant eigenvector / eigenvalue of $H$ using the power method or a related method.

That said, I don’t really like the idea of using this on every solve if it takes a lot of time.   Ideally one would employ the above procedure only when the inertia of the KKT factorisation looks ‘suspicious’, i.e. when the entries of D in the LDL factorisation appear too close to zero.   However, there is no obvious way that I can see to lower bound the positive entries of D given a lower bound on the eigenvalues of the PD part of the KKT matrix.







On 5 Sep 2018, at 22:11, Bartolomeo Stellato <notifications@github.com<mailto:notifications@github.com>> wrote:


There might be cases where this test does not detect a matrix with a slightly negative eigenvalue. As @gbanjac<https://github.com/gbanjac> mentioned, this happens when that eigenvalue is in absolute value less than 1e-06. I think the only way to detect a non PSD matrix in 100% of the cases would be to perform an eigenvalue decomposition inside OSQP. However, we do not want to do that because it can be very slow.

Do you have QPs with these characteristics? Would it be possible for you to check if the problem is convex when you are building it? From which language are you calling OSQP?

**Comment by bstellato** [comment] 2018-09-11 21:29
Thank you @mlubin for the suggestions! It is definitely good to add something more clear in the docs. I agree with @goulart-paul that the 100% sure detection would take too much time.

I have added a comment to `OSQP_NON_CVX` in the docs so that the users know there is some kind of detection, but it is not supersafe: 2e5815a0646544df. It will be merged to the `master` branch with the new release.

**Closed** 2018-09-26 21:11 UTC
